name: Waka Readme Manual

on:
  workflow_dispatch:

jobs:
  wakatime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install wakatime

      - name: Update this repo's README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_DAYS_OF_WEEK: "False"
          COMMIT_BY_ME: "False"
          COMMIT_SINGLE: "False"
          HIDE_PROJECT_FOLDER: "true"
          HIDE_BRANCH_NAMES: "true"
          HIDE_FILE_NAMES: "true"
          OUTPUT_FORMAT: "json"
